name: Test and tag

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  test-and-tag:
    name: Test and tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: true

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run checks
        run: |
          cargo fmt --check
          cargo clippy
          cargo test

      - name: Get version, check if tag exists, create if not
        env:
          GITHUB_TOKEN: ${{ secrets.PUSH_TAG_PAT }}
        run: |
          VERSION=$(cargo pkgid | | rev | cut -d '@' -f 1 | cut -d '#' -f 1 | rev)
          TAG="v${VERSION}"
          if git ls-remote --tags origin "refs/tags/${TAG}" | grep -q "refs/tags/${TAG}"; then
            echo "Tag ${TAG} already exists"
          else
            echo "Creating tag ${TAG}"
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag "${TAG}"
            git push origin "${TAG}"
          fi
