name: Test and tag

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  test-and-tag:
    name: Test and tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-tags: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run checks
        run: |
          cargo fmt --check
          cargo clippy
          cargo test

      - name: Get version
        id: get_tag
        run: |
          VERSION=$(cargo pkgid | cut -d @ -f 2)
          echo "tag=v${VERSION}" >> $GITHUB_OUTPUT
          echo "Create tag ${TAG} if not exists"

      - name: Create and push tag
        uses: actions-ecosystem/action-create-tag@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.get_tag.outputs.tag }}
          force_push_tag: false
